const C=window.APP_CONFIG||{};const KEY="rtrw_sid_trial_v1",DAYS=7;let sb=null,state={view:"dashboard",sub:"overview"};
const modules={
dashboard:["Command Center",["overview","approvals","tasks","activity"]],
warga:["Warga Portal",["registry","household","address","services","complaints"]],
rt:["RT Digital",["residents","verification","letters","activities","security","social","dues"]],
rw:["RW Digital",["consolidation","review","programs","coordination","security","indicators"]],
kegiatan:["Kegiatan & Musyawarah",["calendar","meeting","attendance","minutes","reminder"]],
layanan:["Pelayanan & Pengaduan",["queue","requests","complaints","tracking","sla"]],
desa:["Desa Digital",["validation","services","development","assets","regulation","transparency"]],
dokumen:["Dokumen & TTE",["inbox","compose","approval","signing","verification","archive"]],
dataquality:["Data Quality",["score","queue","duplicate","consistency","repair"]],
smart:["Smart Village",["command","people","government","economy","living","environment","mobility","innovation"]],
jolie:["Jolie Business OS",["crm","customers","suppliers","inventory","sales","purchasing","accounting","marketplace","bi"]],
gis:["GIS",["map","layers","assets","geofence","analysis","privacy"]],
whatsapp:["WhatsApp Gateway",["inbox","templates","notifications","delivery","consent","broadcast"]],
sid:["SID Bridge",["mapping","sync","validation","conflict","logs"]],
gpffe:["GPFFE Data Exchange",["catalog","requests","exports","audit","contract"]],
admin:["Admin & Governance",["tenant","territory","users","roles","policies","templates","security","audit","backup","health"]]
const demo={kpi:[["1,284","Warga","+4.8% bulan ini"],["326","Kartu Keluarga","Data terstruktur"],["48","Layanan aktif","12 perlu review"],["17","Menunggu verifikasi","RT/RW queue"]],activity:[["08:42","Pengajuan surat pengantar","RT 04","SUBMITTED"],["08:18","Review data keluarga","RW 02","RW_REVIEWED"],["07:55","Validasi layanan","Desa Demo","AUTHORIZED"],["Kemarin","Dataset kebutuhan komunitas","GPFFE","VERIFIED"]],queue:[["REQ-240928-014","Surat pengantar","RT 04","Menunggu"],["REQ-240928-011","Perubahan data warga","RT 02","Review"],["REQ-240927-098","Kegiatan warga","RT 07","Menunggu"]]};
const esc=v=>String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));const trial=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"null")}catch{return null}};const active=()=>{const t=trial();return !!(t&&Date.now()<t.expiresAt)};const current=async()=>sb?(await sb.auth.getUser()).data.user||null:null;
function startTrial(){const n=Date.now();localStorage.setItem(KEY,JSON.stringify({startedAt:n,expiresAt:n+DAYS*86400000}));render()}function closeModal(e){if(!e||e.target===e.currentTarget||!e.target.closest?.(".modal-card"))document.getElementById("modal")?.remove()}
function modal(title,body){let x=document.getElementById("modal");if(!x){x=document.createElement("div");x.id="modal";document.body.appendChild(x)}x.innerHTML=`<div class="modal-backdrop" onclick="closeModal(event)"><div class="modal-card" onclick="event.stopPropagation()"><button class="modal-x" onclick="closeModal()">×</button><div class="modal-kicker">RT/RW–SID CONNECT</div><h3>${esc(title)}</h3>${body}</div></div>`}
async function submitSignIn(){const email=document.getElementById("auth-email")?.value.trim();if(!email)return;const r=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}}),m=document.getElementById("auth-msg");if(r.error){m.textContent=r.error.message;m.className="modal-msg error"}else{m.textContent="Link akses telah dikirim. Periksa inbox Anda.";m.className="modal-msg success"}}
function signIn(){if(!sb){modal("Konfigurasi belum siap","<p>Supabase belum terhubung. Hubungi administrator pilot.</p>");return}modal("Masuk ke workspace",'<p>Gunakan email untuk menerima link akses tanpa password.</p><label>Email</label><input id="auth-email" type="email" autocomplete="email" placeholder="nama@contoh.id"><button class="primary" onclick="submitSignIn()">Kirim Link Akses</button><div id="auth-msg" class="modal-msg"></div>')}
async function signOut(){if(sb)await sb.auth.signOut();localStorage.removeItem(KEY);render()}
function landing(){document.getElementById("landing").innerHTML=`<div class="landing"><header><div class="brand"><b>RS</b><span>RT/RW–SID CONNECT<small>COMMUNITY · VILLAGE · SMART VILLAGE OS</small></span></div><span class="pilot">FREE-FIRST PILOT · v2.0</span></header><main><section><div class="eyebrow">DIGITAL OPERATING PLATFORM</div><h1>Satu operating system untuk <em>komunitas & desa.</em></h1><p>Hubungkan Warga, RT, RW, Desa, Smart Village, Jolie Business OS, GPFFE, GIS dan governance dalam satu core data platform.</p><div class="actions"><button onclick="signIn()">Sign In</button><button class="ghost" onclick="startTrial()">Coba Trial 7 Hari</button></div><div class="trust"><span>✓ Tanpa kartu kredit</span><span>✓ Trial anonim</span><span>✓ Privacy by design</span></div></section><div class="landing-preview"><div class="preview-chrome"><span>● ● ●</span><b>community-data-os</b><i>TRIAL</i></div><div class="preview-shell"><aside><strong>RS</strong><div class="pnav active">⌂</div><div class="pnav">♙</div><div class="pnav">▣</div><div class="pnav">◈</div></aside><article><div class="preview-head"><small>COMMAND CENTER</small><b>Operational Overview</b></div><div class="preview-kpis"><div><strong>1,284</strong><small>Warga</small></div><div><strong>326</strong><small>KK</small></div><div><strong>48</strong><small>Layanan</small></div></div><div class="preview-chart"><span style="height:42%"></span><span style="height:60%"></span><span style="height:50%"></span><span style="height:76%"></span><span style="height:68%"></span><span style="height:90%"></span><span style="height:82%"></span></div><div class="preview-row"><span>Progressive verification</span><b>86%</b></div></article></div></div></main><footer>RT/RW–SID CONNECT v2.0 · Community, Village & Smart Village Digital Operating Platform</footer></div>`}
function icon(k){return{dashboard:"⌂",warga:"♙",rt:"R",rw:"W",kegiatan:"◷",layanan:"▣",desa:"D",dokumen:"▤",dataquality:"✓",smart:"✦",jolie:"◫",gis:"⌖",whatsapp:"◌",sid:"↔",gpffe:"⇄",admin:"⚙"}[k]||"•"}
const navGroups=[["CORE",["dashboard","warga","rt","rw","kegiatan","layanan"]],["VILLAGE",["desa","dokumen","dataquality"]],["INTELLIGENCE",["smart","jolie"]],["INTEGRATION",["gis","whatsapp","sid","gpffe"]],["GOVERNANCE",["admin"]]];
function nav(){return navGroups.map(g=>`<div class="nav-group"><small>${g[0]}</small>${g[1].map(k=>`<button class="${state.view===k?"active":""}" onclick="go('${k}','${modules[k][1][0]}')"><span class="nav-icon">${icon(k)}</span>${modules[k][0]}</button>`).join("")}</div>`).join("")}

function go(v,s){state.view=v;state.sub=s;render()}function label(s){return s.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}function subnav(){return modules[state.view][1].map(s=>`<button class="${state.sub===s?"active":""}" onclick="go('${state.view}','${s}')">${label(s)}</button>`).join("")}
async function profile(){if(!sb)return null;const u=await current();if(!u)return null;let q=await sb.from("role_assignments").select("role_id,scope_territory_id,organization_id,active,roles(role_code,role_name),territories:scope_territory_id(name,territory_type)").eq("user_id",u.id).eq("active",true);if(q.error?.code==="42501")return{user:u,assignments:[],roleError:"Role belum dapat dibaca oleh akun ini."};if(!q.error&&!q.data?.length){const boot=await sb.functions.invoke("bootstrap-pilot",{body:{}});if(boot.error)console.warn("Pilot bootstrap",boot.error);q=await sb.from("role_assignments").select("role_id,scope_territory_id,organization_id,active,roles(role_code,role_name),territories:scope_territory_id(name,territory_type)").eq("user_id",u.id).eq("active",true)}return{user:u,assignments:q.data||[],roleError:q.error?.message||""}}
function status(t){return`<span class="status ${String(t).toLowerCase().replaceAll("_","-")}">${esc(String(t).replaceAll("_"," "))}</span>`}
function dashboard(){return`<div class="welcome"><div><div class="eyebrow dark">COMMAND CENTER / OVERVIEW</div><h2>Selamat datang di <em>Desa Demo.</em></h2><p>Operational snapshot komunitas, pelayanan dan governance dalam satu layar.</p></div><div class="date-chip">● CORE ONLINE<br><small>28 September 2026</small></div></div><div class="kpi-grid">${demo.kpi.map(x=>`<div class="kpi-card"><div class="kpi-top"><span>${x[1]}</span><i>◈</i></div><strong>${x[0]}</strong><small>${x[2]}</small><div class="spark"><b></b><b></b><b></b><b></b><b></b></div></div>`).join("")}</div><div class="dashboard-grid"><section class="panel wide"><div class="panel-head"><div><small>WORKFLOW</small><h3>Progressive Verification</h3></div><span class="mini-badge">LIVE</span></div><div class="pipeline">${["DRAFT","SUBMITTED","RT VERIFIED","RW REVIEWED","VILLAGE VALIDATED","AUTHORIZED"].map((x,i)=>`<div class="${i<4?"done":i===4?"current":""}"><b>${i+1}</b><span>${x}</span></div>`).join("")}</div><div class="progress-line"><span style="width:78%"></span></div><div class="pipeline-foot"><span>78% flow selesai sesuai SLA</span><b>Audit ready</b></div></section><section class="panel"><div class="panel-head"><div><small>APPROVAL QUEUE</small><h3>Menunggu tindakan</h3></div><button class="text-btn" onclick="go('dashboard','approvals')">Lihat semua →</button></div><div class="queue">${demo.queue.map(x=>`<div><span class="queue-dot"></span><div><b>${x[0]}</b><small>${x[1]} · ${x[2]}</small></div>${status(x[3])}</div>`).join("")}</div></section><section class="panel"><div class="panel-head"><div><small>SMART VILLAGE</small><h3>Village Pulse</h3></div><button class="text-btn" onclick="go('smart','command')">Open →</button></div><div class="pulse"><div class="ring"><strong>82</strong><small>INDEX</small></div><div class="pulse-list"><span>Smart Government <b>88%</b></span><span>Smart Economy <b>79%</b></span><span>Smart Living <b>84%</b></span><span>Environment <b>76%</b></span></div></div></section><section class="panel wide"><div class="panel-head"><div><small>ACTIVITY STREAM</small><h3>Aktivitas terbaru</h3></div><button class="text-btn">Audit log →</button></div><div class="activity-list">${demo.activity.map(x=>`<div><time>${x[0]}</time><div><b>${x[1]}</b><small>${x[2]}</small></div>${status(x[3])}</div>`).join("")}</div></section></div>`}
const descriptions={warga:["Warga Portal","Data warga, KK, alamat, layanan dan pengaduan dengan identity model terpisah."],rt:["RT Digital","Workspace operasional RT untuk verifikasi, surat, kegiatan, keamanan, sosial dan iuran."],rw:["RW Digital","Konsolidasi RT, review, koordinasi program dan indikator wilayah."],desa:["Desa Digital","Validasi desa, pelayanan, pembangunan, aset, regulasi dan transparansi."],smart:["Smart Village","Data → Indicator → Insight → Action → Monitoring untuk desa cerdas."],jolie:["Jolie Business OS","Smart Economy & Commerce Engine untuk UMKM, BUM Desa, koperasi dan perdagangan."],gpffe:["GPFFE Data Exchange","Pertukaran dataset terkontrol dengan contract, approval, lineage dan audit."],gis:["GIS","Spatial data, layers, assets, geofence, analysis dan privacy-aware mapping."],admin:["Admin & Governance","Platform control tower: role, scope, permission, policy, security, audit dan health."]};
function workspace(){const d=descriptions[state.view]||["Command Center","Operational workspace"];const vals={warga:["Registry Warga","1,284","KK & Household","326","Layanan","48"],rt:["Verifikasi","17","Surat","24","Kegiatan","12"],rw:["RT Terhubung","8","Review","6","Indikator","82%"],desa:["Validasi","6","Pembangunan","14","Transparansi","92%"],smart:["Village Index","82 / 100","Indicator","24","Action","8"],jolie:["Pelaku Usaha","148","Produk","426","Transaksi","Rp 184 jt"],gpffe:["Dataset","2","Request","4","Export","1"],gis:["Layers","12","Assets","86","Coverage","94%"],admin:["Users","32","Roles","5"]}[state.view]||["Records","—","Workflow","—","Audit","Ready"];return`<div class="module-head"><div><div class="eyebrow dark">${esc(d[0].toUpperCase())} / ${esc(label(state.sub).toUpperCase())}</div><h2>${esc(d[0])}</h2><p>${esc(d[1])}</p></div><button class="primary compact" onclick="application()">＋ New action</button></div><div class="subnav">${subnav()}</div><div class="module-kpis">${[0,2,4].map(i=>`<div><small>${vals[i]}</small><strong>${vals[i+1]}</strong><span>● Updated just now</span></div>`).join("")}</div><div class="workspace-grid"><section class="panel wide"><div class="panel-head"><div><small>OPERATIONAL WORKSPACE</small><h3>${esc(label(state.sub))}</h3></div>${status("AUDIT_READY")}</div><div class="empty-table"><div class="table-head"><span>ITEM</span><span>OWNER / SCOPE</span><span>STATUS</span><span>ACTION</span></div>${["Data komunitas pilot","Pengajuan layanan","Workflow verifikasi","Dataset terkontrol"].map((x,i)=>`<div class="table-row"><b>${x}</b><span>${i%2?"RT 04":"Desa Demo"}</span>${status(["VERIFIED","SUBMITTED","REVIEW","AUTHORIZED"][i])}<button class="row-action" onclick="application()">View</button></div>`).join("")}</div></section><section class="panel"><div class="panel-head"><div><small>GOVERNANCE</small><h3>Control checklist</h3></div></div><div class="checks"><span>✓ Scope authorization</span><span>✓ Data classification</span><span>✓ Purpose binding</span><span>✓ Audit trail</span><span>✓ Human approval gate</span></div></section></div>`}
function application(){if(!sb){modal("Pilot action","<p>Trial dapat mengeksplorasi workspace dengan data simulasi. Penyimpanan pengajuan memerlukan koneksi Supabase.</p>");return}modal("New action",'<p>Contoh input aman untuk pilot. Data resmi tetap mengikuti scope dan verifikasi bertingkat.</p><label>Nama pemohon / objek</label><input id="request-name" autocomplete="name" placeholder="Nama"><button class="primary" onclick="submitApplication()">Simpan Pengajuan</button><div id="request-msg" class="modal-msg"></div>')}
async function submitApplication(){const name=document.getElementById("request-name")?.value.trim();if(!name)return;const u=await current();if(!u){closeModal();signIn();return}const r=await sb.from("demo_requests").insert({request_number:"REQ-"+Date.now(),requester_name:name,service_type:modules[state.view][0]+" / "+state.sub,status:"SUBMITTED"});if(r.error){const m=document.getElementById("request-msg");if(m)m.textContent=r.error.message}else{closeModal();render()}}
async function render(){let p=null;try{p=await profile()}catch(e){console.error(e)}const u=p?.user||null;if(!u&&!active()){document.getElementById("app").innerHTML="";landing();return}document.getElementById("landing").innerHTML="";const role=p?.assignments?.map(x=>x.roles?.role_name||x.roles?.role_code).filter(Boolean).join(" · ")||"Pilot Viewer",scope=p?.assignments?.map(x=>x.territories?.name).filter(Boolean).join(" · ")||"Desa Demo";document.getElementById("app").innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="sidebrand"><b>RS</b><div><strong>RT/RW–SID</strong><small>CONNECT · v2.0</small></div></div><div class="tenant-card"><span>PILOT TENANT</span><strong>Desa Demo</strong><small>Kabupaten Demo · Jawa Barat</small></div><nav>${nav()}</nav><div class="side-foot"><span class="online-dot"></span><div><b>Core online</b><small>Supabase · Secure</small></div></div></aside><main class="app-main"><header class="topbar"><button class="mobile-menu" onclick="document.body.classList.toggle('menu-open')">☰</button><div class="crumb"><small>COMMUNITY DATA OS</small><b>${esc(modules[state.view][0])}</b></div><div class="top-actions"><button class="icon-btn">⌕</button><button class="icon-btn">◌</button><div class="profile"><div class="avatar">${u?(u.email||"U")[0].toUpperCase():"T"}</div><div><b>${esc((u?.email||"Trial").split("@")[0])}</b><small>${esc(role)} · ${esc(scope)}</small></div>${u?"<button class='signout' onclick='signOut()'>Sign out</button>":""}</div></div></header><div class="content">${state.view==="dashboard"?dashboard():workspace()}</div></main></div>`}
window.signIn=signIn;window.startTrial=startTrial;window.signOut=signOut;window.go=go;window.application=application;window.submitSignIn=submitSignIn;window.submitApplication=submitApplication;window.closeModal=closeModal;
if(C.supabasePublishableKey&&window.supabase)sb=supabase.createClient(C.supabaseUrl,C.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});if(sb)sb.auth.onAuthStateChange(()=>render());render();