(()=>{const sb=window.supabase?.createClient(window.APP_CONFIG?.supabaseUrl||"",window.APP_CONFIG?.supabasePublishableKey||"",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const toast=document.getElementById("toast"),toastText=toast?.querySelector("span"),modal=document.getElementById("actionModal"),content=document.getElementById("modalContent");let timer;
const areas={all:{label:"Semua wilayah",rt:"Seluruh RT",rw:"Seluruh RW",focus:"Pusat Desa"},rt01:{label:"RT 01 · RW 01",rt:"RT 01",rw:"RW 01",focus:"Lingkungan RT 01"},rt02:{label:"RT 02 · RW 01",rt:"RT 02",rw:"RW 01",focus:"Lingkungan RT 02"},rt03:{label:"RT 03 · RW 01",rt:"RT 03",rw:"RW 01",focus:"Lingkungan RT 03"},rt04:{label:"RT 04 · RW 02",rt:"RT 04",rw:"RW 02",focus:"Lingkungan RT 04"},rt05:{label:"RT 05 · RW 02",rt:"RT 05",rw:"RW 02",focus:"Lingkungan RT 05"}};
const services=[
{key:"population",title:"Administrasi Kependudukan",icon:"bi-file-earmark-person",desc:"Informasi persyaratan dan alur layanan kependudukan sesuai kewenangan.",action:"Lihat persyaratan",intro:"Pilih jenis layanan untuk melihat persyaratan dan tahapan. Pengajuan resmi akan mengikuti alur verifikasi RT/RW/Desa dan proses berwenang.",items:[["KK","Kartu Keluarga","Informasi pengajuan baru, perubahan, atau penyesuaian data."],["KTP-el","KTP-el","Informasi perekaman, perubahan, dan dokumen pendukung."],["KIA","KIA","Informasi layanan Kartu Identitas Anak."],["Perubahan Data","Perubahan data","Informasi koreksi elemen data kependudukan."],["Kelahiran","Kelahiran","Informasi pelaporan dan dokumen pendukung kelahiran."],["Kematian","Kematian","Informasi pelaporan peristiwa kematian."],["Perpindahan","Perpindahan","Informasi perpindahan penduduk dan dokumen terkait."]]},
{key:"complaint",title:"Pengaduan Warga",icon:"bi-megaphone",desc:"Sampaikan laporan lingkungan, fasilitas, keamanan, sosial, dan pelayanan.",action:"Buat laporan",intro:"Pilih kategori laporan. Untuk laporan yang memerlukan tindak lanjut, sistem akan meminta konteks wilayah dan kontak yang diperlukan.",items:[["Lingkungan","Lingkungan","Sampah, drainase, jalan, penerangan, dan kebersihan."],["Fasilitas","Fasilitas publik","Kerusakan atau kebutuhan fasilitas umum."],["Keamanan","Keamanan","Informasi gangguan keamanan atau ketertiban."],["Sosial","Sosial","Informasi masalah sosial dan kebutuhan warga."],["Pelayanan","Pelayanan desa","Masukan atau kendala pada pelayanan."]]},
{key:"letter",title:"Surat & Pelayanan Desa",icon:"bi-envelope-paper",desc:"Temukan jenis surat dan informasi pengajuan sesuai kewenangan desa.",action:"Lihat jenis layanan",intro:"Katalog ini menjadi pintu informasi sebelum warga mengajukan pelayanan.",items:[["Domisili","Surat keterangan domisili","Informasi persyaratan dan tujuan penggunaan."],["Usaha","Surat keterangan usaha","Informasi dokumen pendukung usaha."],["Pengantar","Surat pengantar","Jenis pengantar yang tersedia melalui desa/RT/RW."],["Lainnya","Pelayanan administrasi lainnya","Katalog layanan akan mengikuti kewenangan dan kebijakan desa."]]},
{key:"activities",title:"Kegiatan RT/RW",icon:"bi-calendar2-week",desc:"Agenda musyawarah, kerja bakti, sosial, komunitas, dan kegiatan desa.",action:"Lihat kegiatan",intro:"Pilih konteks kegiatan untuk melihat agenda yang relevan dengan wilayah Anda.",items:[["RT","Kegiatan RT","Kerja bakti, rapat RT, sosial, dan pengumuman."],["RW","Kegiatan RW","Musyawarah dan kegiatan lintas RT."],["Desa","Kegiatan Desa","Agenda pelayanan, pembangunan, musyawarah, dan desa."],["Komunitas","Komunitas","Kegiatan sosial, olahraga, budaya, dan komunitas."]]},
{key:"tracking",title:"Lacak Permohonan",icon:"bi-clipboard2-check",desc:"Pantau status permohonan setelah warga masuk ke akun.",action:"Masuk & lacak",intro:"Gunakan akun warga untuk melihat permohonan, tahapan verifikasi, catatan perbaikan, dan hasil layanan.",items:[["Aktif","Permohonan aktif","Melihat permohonan yang sedang diproses."],["Riwayat","Riwayat layanan","Melihat riwayat pengajuan yang pernah dibuat."],["Notifikasi","Notifikasi","Pemberitahuan perubahan status dan tindakan yang diperlukan."]]},
{key:"public-data",title:"Data Publik",icon:"bi-bar-chart",desc:"Indikator desa dan informasi publik yang aman untuk ditampilkan.",action:"Lihat data",intro:"Data publik ditampilkan dalam bentuk yang tidak membuka data pribadi atau data operasional terbatas.",items:[["Demografi","Demografi agregat","Ringkasan penduduk tanpa membuka identitas personal."],["Pembangunan","Pembangunan","Program, indikator, dan perkembangan pembangunan."],["Layanan","Layanan","Ringkasan aktivitas pelayanan secara agregat."],["Ekonomi","Ekonomi lokal","Ringkasan UMKM dan potensi ekonomi."]]}
];
function showToast(m){if(!toast)return;toastText.textContent=m;toast.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove("show"),3000)}
function openModal(html){content.innerHTML=html;modal.classList.add("show");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open")}
function closeModal(){modal.classList.remove("show");modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
function currentArea(){return localStorage.getItem("sv_area")||"all"}
function applyArea(key){const a=areas[key]||areas.all;localStorage.setItem("sv_area",key);const c=document.getElementById("mapContext"),l=document.getElementById("mapAreaLabel"),t=document.getElementById("mapTitle");if(c)c.innerHTML=`<i class="bi bi-people"></i> ${a.label}`;if(l)l.textContent=a.focus;if(t)t.textContent=key==="all"?"Peta Kehidupan Desa":`Peta · ${a.rt} / ${a.rw}`;document.querySelectorAll(".map-pin").forEach((p,i)=>p.classList.toggle("area-focus",key!=="all"&&i===0))}
function areaModal(){openModal(`<span class="eyebrow dark">PERSONALISASI WILAYAH</span><h2 class="modal-title">Peta sesuai RT/RW Anda</h2><p class="modal-copy">Pilih wilayah yang ingin Anda lihat. Pilihan disimpan di perangkat ini; setelah akun warga tersedia, wilayah dapat diambil otomatis dari profil dan cakupan RT/RW.</p><div class="area-grid">${Object.entries(areas).map(([k,a])=>`<button class="area-option ${k===currentArea()?"selected":""}" data-area="${k}"><strong>${a.rt}</strong><span>${a.rw}</span><small>${a.label}</small></button>`).join("")}</div><div class="modal-note"><i class="bi bi-shield-check"></i> Data pribadi dan data operasional RT/RW tetap berada di batas aksesnya.</div>`)}
function serviceModal(selected){const s=services.find(x=>x.key===selected)||services[0];openModal(`<span class="eyebrow dark">LAYANAN PUBLIK</span><h2 class="modal-title">${s.title}</h2><p class="modal-copy">${s.intro}</p><div class="service-menu">${services.map(x=>`<button class="service-menu-item ${x.key===s.key?"selected":""}" data-service="${x.key}"><i class="bi ${x.icon}"></i><span><strong>${x.title}</strong><small>${x.action}</small></span><i class="bi bi-arrow-right"></i></button>`).join("")}</div><div class="service-detail-grid">${s.items.map((x,i)=>`<button class="service-detail-card" data-service-item="${s.key}" data-item="${i}"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small><i class="bi bi-arrow-up-right"></i></button>`).join("")}</div><div class="modal-detail"><strong>Yang tampil pada layanan ini</strong><ol><li>Informasi persyaratan dan dokumen pendukung.</li><li>Alur pengajuan dan pihak yang memproses.</li><li>Status permohonan dan tindakan yang diperlukan.</li><li>Catatan batas kewenangan: website tidak menerbitkan dokumen pemerintah yang menjadi kewenangan instansi resmi.</li></ol><button class="btn btn-civic" data-service-start="${s.key}">${s.action} <i class="bi bi-arrow-up-right ms-1"></i></button></div>`)}
function itemModal(serviceKey,index){const s=services.find(x=>x.key===serviceKey),x=s?.items[index];if(!s||!x)return;const isPopulation=s.key==="population";openModal(`<span class="eyebrow dark">${s.title}</span><h2 class="modal-title">${x[1]}</h2><p class="modal-copy">${x[2]}</p><div class="flow-box"><strong>Alur layanan</strong><div class="flow-line"><span>Warga</span><i class="bi bi-arrow-right"></i><span>RT</span><i class="bi bi-arrow-right"></i><span>RW</span><i class="bi bi-arrow-right"></i><span>Desa</span><i class="bi bi-arrow-right"></i><span>Proses berwenang</span></div></div><div class="requirements"><strong>Informasi yang akan ditampilkan</strong><div><i class="bi bi-check2"></i> Persyaratan dan dokumen pendukung</div><div><i class="bi bi-check2"></i> Tahapan pengajuan dan verifikasi</div><div><i class="bi bi-check2"></i> Perkiraan status/tindakan berikutnya</div><div><i class="bi bi-check2"></i> Informasi kontak/unit pelayanan</div></div><div class="modal-cta"><button class="btn btn-civic" data-start-item="${s.key}" data-item-index="${i}">${isPopulation?"Masuk ke pengajuan":"Mulai layanan"} <i class="bi bi-arrow-right ms-1"></i></button><button class="btn btn-outline-civic" data-service-back="${s.key}">Kembali ke layanan</button></div>`)}
async function currentUser(){if(!sb)return null;const {data:{user},error}=await sb.auth.getUser();if(error)throw error;return user||null}
function loginRequired(){openModal('<span class="eyebrow dark">AKUN WARGA</span><h2 class="modal-title">Masuk ke SIM RT/RW</h2><p class="modal-copy">Untuk mengirim formulir resmi, silakan masuk terlebih dahulu melalui aplikasi SIM RT/RW–SID. Setelah login, kembali ke website ini pada perangkat yang sama.</p><div class="login-choice"><a class="btn btn-civic" href="../">Buka SIM RT/RW</a><button class="btn btn-outline-civic" data-close-modal>Tutup</button></div><div class="modal-note mt-3"><i class="bi bi-shield-check"></i> Sesi autentikasi menggunakan Supabase Auth yang sama.</div>')}
function territoryForArea(){return "f06b8420-54f5-4ee4-b487-bacc7b374dd2"}
const formDefs={
"population:0":{title:"KK · Kartu Keluarga",service:"HOUSEHOLD",fields:[["applicant_name","Nama pemohon","text",true],["applicant_nik","NIK pemohon","text",false],["household_number","Nomor KK saat ini","text",false],["request_type","Jenis pengajuan","select",true,["KK Baru","Perubahan data","Penyesuaian data"]],["address","Alamat","text",true],["rt","RT","text",true],["rw","RW","text",true],["members","Anggota keluarga (satu nama per baris)","textarea",true]]},
"population:1":{title:"KTP-el",service:"KTP_EL",fields:[["full_name","Nama lengkap","text",true],["nik","NIK","text",true],["reason","Keperluan/perubahan","textarea",true],["address","Alamat","text",true],["rt","RT","text",true],["rw","RW","text",true]]},
"population:2":{title:"KIA · Kartu Identitas Anak",service:"KIA",fields:[["child_name","Nama anak","text",true],["child_nik","NIK anak (jika ada)","text",false],["parent_name","Nama orang tua/wali","text",true],["reason","Keperluan","textarea",true],["address","Alamat","text",true],["rt","RT","text",true],["rw","RW","text",true]]},
"population:3":{title:"Perubahan Data Kependudukan",service:"DATA_CHANGE",fields:[["full_name","Nama lengkap","text",true],["nik","NIK","text",true],["changed_element","Elemen data yang diubah","text",true],["old_value","Data sebelumnya","text",true],["new_value","Data yang benar","text",true],["reason","Alasan perubahan","textarea",true]]},
"population:4":{title:"Pelaporan Kelahiran",service:"BIRTH",fields:[["child_name","Nama bayi/anak","text",true],["birth_date","Tanggal lahir","date",true],["birth_place","Tempat lahir","text",true],["father_name","Nama ayah","text",true],["mother_name","Nama ibu","text",true],["address","Alamat","text",true],["rt","RT","text",true],["rw","RW","text",true]]},
"population:5":{title:"Pelaporan Kematian",service:"DEATH",fields:[["deceased_name","Nama almarhum/almarhumah","text",true],["nik","NIK","text",true],["date_of_death","Tanggal kematian","date",true],["place_of_death","Tempat kematian","text",true],["cause_category","Kategori sebab","select",true,["Sakit","Kecelakaan","Usia lanjut","Lainnya"]],["address","Alamat terakhir","text",true],["rt","RT","text",true],["rw","RW","text",true]]},
"population:6":{title:"Perpindahan Penduduk",service:"MOVE",fields:[["full_name","Nama lengkap","text",true],["nik","NIK","text",true],["origin_address","Alamat asal","textarea",true],["destination_address","Alamat tujuan","textarea",true],["reason","Alasan pindah","textarea",true],["rt","RT asal","text",true],["rw","RW asal","text",true]]},
"complaint:0":{title:"Pengaduan · Lingkungan",service:"COMPLAINT",fields:[["category","Kategori","text",true],["location","Lokasi","text",true],["summary","Ringkasan laporan","textarea",true],["detail","Uraian lengkap","textarea",true]]},
"complaint:1":{title:"Pengaduan · Fasilitas Publik",service:"COMPLAINT",fields:[["category","Kategori","text",true],["location","Lokasi fasilitas","text",true],["summary","Ringkasan masalah","textarea",true],["detail","Uraian lengkap","textarea",true]]},
"complaint:2":{title:"Pengaduan · Keamanan",service:"COMPLAINT",fields:[["category","Kategori","text",true],["location","Lokasi kejadian","text",true],["summary","Ringkasan kejadian","textarea",true],["detail","Uraian lengkap","textarea",true]]},
"complaint:3":{title:"Pengaduan · Sosial",service:"COMPLAINT",fields:[["category","Kategori","text",true],["location","Wilayah","text",true],["summary","Ringkasan kebutuhan","textarea",true],["detail","Uraian lengkap","textarea",true]]},
"complaint:4":{title:"Pengaduan · Pelayanan",service:"COMPLAINT",fields:[["category","Kategori","text",true],["location","Unit/layanan","text",true],["summary","Ringkasan kendala","textarea",true],["detail","Uraian lengkap","textarea",true]]},
"letter:0":{title:"Surat Keterangan Domisili",service:"LETTER_DOMISILE",fields:[["full_name","Nama pemohon","text",true],["nik","NIK","text",true],["purpose","Tujuan surat","textarea",true],["address","Alamat","text",true],["rt","RT","text",true],["rw","RW","text",true]]},
"letter:1":{title:"Surat Keterangan Usaha",service:"LETTER_BUSINESS",fields:[["full_name","Nama pemohon","text",true],["nik","NIK","text",true],["business_name","Nama usaha","text",true],["business_type","Jenis usaha","text",true],["business_address","Alamat usaha","textarea",true]]},
"letter:2":{title:"Surat Pengantar",service:"LETTER_INTRO",fields:[["full_name","Nama pemohon","text",true],["nik","NIK","text",true],["purpose","Keperluan","textarea",true],["destination","Tujuan pengantar","text",true],["rt","RT","text",true],["rw","RW","text",true]]},
"letter:3":{title:"Pelayanan Administrasi Lainnya",service:"LETTER_OTHER",fields:[["full_name","Nama pemohon","text",true],["nik","NIK","text",true],["service_detail","Jenis/keperluan layanan","textarea",true],["notes","Catatan tambahan","textarea",true]]},
"activities:0":{title:"Usulan/Kegiatan RT",service:"ACTIVITY_RT",fields:[["title","Judul kegiatan","text",true],["date","Tanggal","date",true],["location","Lokasi","text",true],["description","Deskripsi","textarea",true]]},
"activities:1":{title:"Usulan/Kegiatan RW",service:"ACTIVITY_RW",fields:[["title","Judul kegiatan","text",true],["date","Tanggal","date",true],["location","Lokasi","text",true],["description","Deskripsi","textarea",true]]},
"activities:2":{title:"Usulan/Kegiatan Desa",service:"ACTIVITY_VILLAGE",fields:[["title","Judul kegiatan","text",true],["date","Tanggal","date",true],["location","Lokasi","text",true],["description","Deskripsi","textarea",true]]},
"activities:3":{title:"Usulan Kegiatan Komunitas",service:"ACTIVITY_COMMUNITY",fields:[["title","Nama kegiatan","text",true],["date","Tanggal","date",true],["location","Lokasi","text",true],["description","Deskripsi","textarea",true]]}
};
function fieldHtml(f){const [name,label,type,required,options]=f;if(type==="textarea")return `<label>${label}<textarea name="${name}" ${required?"required":""}></textarea></label>`;if(type==="select")return `<label>${label}<select name="${name}" ${required?"required":""}>${options.map(o=>`<option>${o}</option>`).join("")}</select></label>`;return `<label>${label}<input name="${name}" type="${type}" ${required?"required":""}></label>`}
function publicForm(key){const d=formDefs[key];if(!d)return;openModal(`<span class="eyebrow dark">FORMULIR LAYANAN</span><h2 class="modal-title">${d.title}</h2><p class="modal-copy">Data ini dikirim ke SIM RT/RW–SID sebagai permohonan <strong>${d.service}</strong>. Untuk KK, sumber pengajuan menggunakan F-1.02 dan hasilnya dipetakan ke F-1.09 setelah proses berwenang.</p><form id="svServiceForm" class="form-preview">${d.fields.map(fieldHtml).join("")}<label>Wilayah aktif<input value="${areas[currentArea()].label}" disabled></label><button class="btn btn-civic" type="submit">Kirim pengajuan resmi</button><div class="form-note"><i class="bi bi-shield-check"></i> Website tidak menerbitkan dokumen pemerintah. Permohonan masuk ke alur verifikasi dan proses berwenang.</div><div id="svFormError" class="form-error" role="alert"></div></form>`);document.getElementById("svServiceForm")?.addEventListener("submit",async e=>{e.preventDefault();try{const user=await currentUser();if(!user){loginRequired();return}const payload=Object.fromEntries(new FormData(e.target).entries());if(d.service==="HOUSEHOLD"){payload.request_kk=payload.request_type==="KK Baru";payload.members=payload.members.split(/\n|,/).map(x=>({full_name:x.trim()})).filter(x=>x.full_name)}const resp=await sb.functions.invoke("public-service-request",{body:{service_type:d.service,territory_id:territoryForArea(),payload}});if(resp.error||!resp.data?.ok)throw new Error(resp.data?.error||resp.error?.message||"Pengajuan gagal");closeModal();showToast("✓ Pengajuan masuk ke SIM RT/RW · "+(resp.data.record?.request_number||resp.data.record?.id||"tersimpan"));}catch(x){document.getElementById("svFormError").textContent=x?.message||"Pengajuan gagal";}})}
function startService(key,index){if(key==="tracking"){openTracking();return}if(index!=null){currentUser().then(u=>{if(u)publicForm(key+":"+index);else loginRequired()}).catch(()=>loginRequired());return}serviceModal(key)}
async function openTracking(){try{const u=await currentUser();if(!u){loginRequired();return}const resp=await sb.functions.invoke("public-service-request",{body:{action:"list"}});if(resp.error||!resp.data?.ok)throw new Error(resp.data?.error||resp.error?.message||"Gagal mengambil permohonan");const rows=resp.data.records||[];openModal(`<span class="eyebrow dark">LACAK PERMOHONAN</span><h2 class="modal-title">Permohonan Anda</h2><p class="modal-copy">Status diambil langsung dari SIM RT/RW–SID.</p><div class="tracking-list">${rows.length?rows.map(r=>`<div class="tracking-row"><strong>${r.service_type}</strong><span>${r.status}</span><small>${new Date(r.created_at).toLocaleString("id-ID")} · ${r.request_number||r.id}</small></div>`).join(""):"<div class='modal-note'>Belum ada permohonan.</div>"}</div>`)}catch(x){showToast("Gagal memuat status: "+(x?.message||"kesalahan"))}}
function handleAction(action){if(action==="area"){areaModal();return}if(action==="services"){serviceModal();return}if(services.some(x=>x.key===action)){serviceModal(action);return}const pages={news:["NEWS ENGINE","Berita desa, kegiatan warga, ekonomi lokal, dan informasi publik disusun dalam kategori editorial yang jelas."],article:["ARTIKEL","Artikel lengkap akan tampil dengan tanggal, kategori, penulis/editorial, sumber, dan konten terkait."],chat:["RUANG WARGA","Ruang chat dapat dibagi menjadi Tanya Desa, Pengumuman, Pengaduan, dan Komunitas. Pengguna akan memilih konteks wilayah sebelum berinteraksi."],economy:["JOLIE BUSINESS OS","Direktori UMKM, produk/jasa, agenda ekonomi, dan koneksi pasar lokal."],agenda:["AGENDA WARGA","Kalender kegiatan RT, RW, Desa, pelayanan, musyawarah, gotong royong, dan kegiatan ekonomi."],dashboard:["DASHBOARD PUBLIK","Ringkasan indikator publik yang aman ditampilkan: demografi agregat, pembangunan, layanan, kegiatan, dan ekonomi."],gis:["GIS DESA","Peta publik untuk RT/RW, fasilitas, kegiatan, dan potensi ekonomi dengan batas data yang aman."],privacy:["PRINSIP DATA","Data publik dipisahkan dari data pribadi dan operasional. Akses mengikuti peran, wilayah, tujuan, dan kewenangan."],login:["MASUK WARGA","Login warga akan membuka layanan personal, riwayat permohonan, notifikasi, dan ruang komunikasi sesuai wilayah."]};const p=pages[action];if(p)openModal(`<span class="eyebrow dark">SMART VILLAGE</span><h2 class="modal-title">${p[0]}</h2><p class="modal-copy">${p[1]}</p><div class="modal-cta"><button class="btn btn-civic" data-action="services">Buka menu layanan</button><button class="btn btn-outline-civic" data-close-modal>Tutup</button></div>`)}
document.addEventListener("click",e=>{const action=e.target.closest("[data-action]")?.dataset.action;if(action){e.preventDefault();handleAction(action);return}const area=e.target.closest("[data-area]")?.dataset.area;if(area){applyArea(area);closeModal();showToast("Wilayah aktif: "+areas[area].label);return}const svc=e.target.closest("[data-service]")?.dataset.service;if(svc){serviceModal(svc);return}const item=e.target.closest("[data-service-item]");if(item){itemModal(item.dataset.serviceItem,Number(item.dataset.item));return}const back=e.target.closest("[data-service-back]")?.dataset.serviceBack;if(back){serviceModal(back);return}const start=e.target.closest("[data-service-start]")?.dataset.serviceStart;if(start){startService(start);return}const startItem=e.target.closest("[data-start-item]");if(startItem){startService(startItem.dataset.startItem,Number(startItem.dataset.itemIndex));return}const demo=e.target.closest("[data-demo-submit]")?.dataset.demoSubmit;if(demo){showToast("Draft "+demo+" tersimpan di sesi demo. Belum dikirim sebagai transaksi resmi.");return}if(e.target.closest("[data-close-modal]"))closeModal()});
document.querySelectorAll(".nav-link").forEach(link=>link.addEventListener("click",()=>{document.querySelectorAll(".nav-link").forEach(x=>x.classList.remove("active"));link.classList.add("active")}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const id=entry.target.id;document.querySelectorAll(".nav-link").forEach(link=>link.classList.toggle("active",link.getAttribute("href")==="#"+id))}}),{rootMargin:"-35% 0px -55% 0px"});document.querySelectorAll("main section[id]").forEach(s=>observer.observe(s));applyArea(currentArea());window.smartVillage={showToast,openModal,applyArea,serviceModal};})();